<?php 
$title = 'My tracks';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p><a href="<?php echo $this->url('track', array( 
        'action'=>'add'));?>">Add new track</a></p>

<table class="table">
<tr>
    <th>Title</th>
    <th>Details</th>
    <th>Album Name</th>
    <th>Action</th>
</tr>
<?php foreach($tracks as $track) : ?>
<tr>
    <td><?php echo $this->escapeHtml($track['title']);?></td>
    <td><?php echo $this->escapeHtml($track['details']);?></td>
    <td><?php echo $this->escapeHtml($track['albumName']);?></td>
    <td>
        <a href="<?php echo $this->url('track',
            array('action'=>'edit', 'id' => $track['id']));?>">Edit</a>
        <a href="<?php echo $this->url('track',
            array('action'=>'delete', 'id' => $track['id']));?>">Delete</a>
    </td>
    
</tr>
<?php endforeach; ?>
</table>
