<?php

namespace Album\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AlbumRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlbumRepository extends EntityRepository
{
    public function finderMethod($arguments=""){
        // My custom query etc
        echo "Repository Class";
    }
    
    public function getAlbumsAndEmployees()
    {
         $albumArray = $result = array();
        
        $qb = $this->createQueryBuilder('s')
                ->select("s.id,s.title,s.artist,s.empid");
        $query = $qb->getQuery();
        $albumArray = $query->getResult();
        //var_dump($albumArray);exit;
        foreach($albumArray as $key=>$album)
        {
            $result[$key]['id'] = $album['id'];
            $result[$key]['title'] = $album['title'];
            $result[$key]['artist'] = $album['artist'];
            $result[$key]['empId'] = $album['empid'];
            
        }
        //var_dump($albumArray);exit;
        
        return $albumArray;
    }
    
    public function getAlbumName($albumid)
    {
        $qb = $this->createQueryBuilder('a')
                ->select("a.title")
                ->where("a.id = ?1")
                ->setParameter(1, $albumid)
                ;
        $query = $qb->getQuery();
        
        $albumName = $query->getSingleResult();
        return $albumName['title'];
    }
}
