<?php

namespace Track\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TrackRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrackRepository extends EntityRepository
{
    public function finderMethod($arguments=""){
        // My custom query etc
        echo "Repository Class";
    }
    
    public function getAlbumsAndTracks()
    {
         $trackArray = $result = array();
        //$query = $this->createQuery('SELECT a FROM Album a JOIN Track t WITH a.id = t.albumId');
        
        $qb = $this->createQueryBuilder('t')
                ->select("t.id,t.title,t.details,t.albumid,a.title as albumName")
                //->innerJoin('t', 'Album\Entity\Album', 'a', 'a.id = t.albumId')
                ->join("Album\Entity\Album", "a")
                
                ->where("a.id = t.albumid")
                ;
        $query = $qb->getQuery();
        
        $trackArray = $query->getResult(); 
        //var_dump($query->getSQL());exit;
        foreach($trackArray as $key=>$track)
        {
            $result[$key]['id'] = $track['id'];
            $result[$key]['title'] = $track['title'];
            $result[$key]['details'] = $track['details'];
            //$result[$key]['albumName'] = $this->getEntityManager()->getRepository('Album\Entity\Album')->getAlbumName($track['albumid']);
            $result[$key]['albumName'] = $track['albumName'];
            
        }
       //var_dump($result);exit;
        return $result;
    }
    
    
}
